// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["POSTGRES_URL"],
    // @ts-expect-error directUrl is not yet in the type definition but required by Prisma 7 runtime
    directUrl: process.env["PRISMA_DATABASE_URL"],
  },
});
